export const path = {
  home: '/',
  roulette: '/roulette',
  btcEth: '/btc-eth',
  futures: '/futures',
  setting: '/setting',
  admin: '/admin',
  adminLong: '/admin/long',
  adminRoulette: '/admin/roulette',
  adminBtcEth: '/admin/btcEth',
  adminFutures: '/admin/futures',
  info: '/info',
  amlPolicy: '/info/amlPolicy',
  contact: '/info/contact',
  fairPlay: '/info/fairPlay',
  gamingPolicy: '/info/gamingPolicy',
  messages: '/messages',
};
